# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
permalink: /:title:output_ext
title: 日本XPユーザーグループ 公式サイト
author: 日本XPユーザーグループ
email: xpjug@googlegroups.com
description: >- # this means to ignore newlines until "baseurl:"
  本ユーザグループは主に eXtremeProgramming (以下XP)の普及を目的としたユーザグループです。
  参加者同士が、XPについての交流の場や、研究会、講習会、ワークショップを持てるように定期的に活動をしていく予定です。
  入会料、年会費は無料で、どなたでも入会できます。みなさまの参加をお待ちしております。
domain: "xpjug.github.io"
# baseurl: "/xpjug.github.io/" # the subpath of your site, e.g. /blog
url: "https://xpjug.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: xpjug
github_username: xpjug
google_analytics: G-QSCX6R6X3C

# Build settings
theme: minima
plugins:
  - jekyll-feed
header_pages:
  - pages/about.md
  - pages/xpfestival.md
  - pages/archives.md
minima:
  social_links:
    - title: "Facebook"
      url: "https://www.facebook.com/xpjug"
      icon: "facebook"
    - title: "X"
      url: "https://x.com/xpjug"
      icon: "x"
    - title: "GitHub"
      url: "https://www.github.com/xpjug"
      icon: "github"
  hide_site_feed_link: true      
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
